# Generated by Django 5.0.6 on 2024-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0003_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.PositiveIntegerField(default=1833, primary_key=True, serialize=False),
        ),
    ]
