# Generated by Django 5.0.6 on 2024-05-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0004_views_delete_user_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='views',
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.PositiveIntegerField(default=6776, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reviews',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoty.song'),
        ),
    ]
