# Generated by Django 5.0.6 on 2024-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0006_rename_review_reviews_text_alter_reviews_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.PositiveIntegerField(default=9089, primary_key=True, serialize=False),
        ),
    ]
