# Generated by Django 5.0.6 on 2024-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0008_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.PositiveIntegerField(default=5115, primary_key=True, serialize=False),
        ),
    ]
