# Generated by Django 5.0.6 on 2024-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0009_alter_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.PositiveIntegerField(default=9192, primary_key=True, serialize=False),
        ),
    ]
